"""
Alert Rules Engine Pattern - Universal Business Solution Framework

A declarative, rule-based alert generation system that evaluates entities
against configurable conditions and generates prioritized alerts. Useful for:
- Monitoring dashboards
- Compliance tracking
- Operational alerts
- SLA monitoring
- Risk warnings
- Threshold-based notifications

Extracted from: Contract Oversight System
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Callable, Any, Union
from enum import Enum
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels in descending priority."""
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"
    INFO = "Info"

    @property
    def priority(self) -> int:
        """Numeric priority for sorting (lower = more urgent)."""
        priorities = {
            AlertSeverity.CRITICAL: 1,
            AlertSeverity.HIGH: 2,
            AlertSeverity.MEDIUM: 3,
            AlertSeverity.LOW: 4,
            AlertSeverity.INFO: 5
        }
        return priorities[self]


class AlertCategory(Enum):
    """Categories for organizing alerts."""
    COST = "Cost"
    SCHEDULE = "Schedule"
    COMPLIANCE = "Compliance"
    PERFORMANCE = "Performance"
    SECURITY = "Security"
    OPERATIONAL = "Operational"
    EXPIRATION = "Expiration"
    QUALITY = "Quality"
    CUSTOM = "Custom"


@dataclass
class AlertRule:
    """
    Definition of an alert rule.

    Example:
    ```python
    AlertRule(
        rule_id="cost_overrun_warning",
        name="Cost Overrun Warning",
        description="Triggered when cost variance exceeds 10%",
        severity=AlertSeverity.HIGH,
        category=AlertCategory.COST,
        condition=lambda e: e.get("cost_variance", 0) > 10,
        message_template="Cost overrun of {cost_variance}% detected for {name}"
    )
    ```
    """
    rule_id: str
    name: str
    condition: Callable[[Dict[str, Any]], bool]
    severity: AlertSeverity = AlertSeverity.MEDIUM
    category: AlertCategory = AlertCategory.CUSTOM
    description: str = ""
    message_template: str = ""
    enabled: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Alert:
    """An alert generated by evaluating a rule against an entity."""
    alert_id: str
    rule_id: str
    rule_name: str
    entity_id: str
    entity_name: str
    severity: AlertSeverity
    category: AlertCategory
    message: str
    timestamp: datetime = field(default_factory=datetime.now)
    acknowledged: bool = False
    resolved: bool = False
    context: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "rule_id": self.rule_id,
            "rule_name": self.rule_name,
            "entity_id": self.entity_id,
            "entity_name": self.entity_name,
            "severity": self.severity.value,
            "category": self.category.value,
            "message": self.message,
            "timestamp": self.timestamp.isoformat(),
            "acknowledged": self.acknowledged,
            "resolved": self.resolved,
            "context": self.context
        }


class AlertRulesEngine:
    """
    A declarative rule-based alert generation engine.

    Example usage:
    ```python
    # Create engine with rules
    engine = AlertRulesEngine()

    # Add rules
    engine.add_rule(AlertRule(
        rule_id="budget_warning",
        name="Budget Warning",
        severity=AlertSeverity.HIGH,
        category=AlertCategory.COST,
        condition=lambda e: e.get("budget_variance", 0) > 10,
        message_template="Budget exceeded by {budget_variance}%"
    ))

    engine.add_rule(AlertRule(
        rule_id="deadline_approaching",
        name="Deadline Approaching",
        severity=AlertSeverity.MEDIUM,
        category=AlertCategory.SCHEDULE,
        condition=lambda e: e.get("days_to_deadline", 999) < 7,
        message_template="Only {days_to_deadline} days until deadline"
    ))

    # Evaluate entities
    entities = [
        {"id": "P001", "name": "Project Alpha", "budget_variance": 15, "days_to_deadline": 5},
        {"id": "P002", "name": "Project Beta", "budget_variance": 5, "days_to_deadline": 30},
    ]

    alerts = engine.evaluate_all(entities)
    # Returns alerts sorted by severity
    ```
    """

    def __init__(self, rules: Optional[List[AlertRule]] = None):
        """Initialize engine with optional list of rules."""
        self.rules: Dict[str, AlertRule] = {}
        self._alert_counter = 0

        if rules:
            for rule in rules:
                self.add_rule(rule)

    def add_rule(self, rule: AlertRule) -> None:
        """Add a rule to the engine."""
        self.rules[rule.rule_id] = rule
        logger.debug(f"Added rule: {rule.rule_id}")

    def remove_rule(self, rule_id: str) -> bool:
        """Remove a rule by ID."""
        if rule_id in self.rules:
            del self.rules[rule_id]
            return True
        return False

    def enable_rule(self, rule_id: str) -> bool:
        """Enable a rule."""
        if rule_id in self.rules:
            self.rules[rule_id].enabled = True
            return True
        return False

    def disable_rule(self, rule_id: str) -> bool:
        """Disable a rule."""
        if rule_id in self.rules:
            self.rules[rule_id].enabled = False
            return True
        return False

    def evaluate_entity(
        self,
        entity: Dict[str, Any],
        id_field: str = "id",
        name_field: str = "name"
    ) -> List[Alert]:
        """
        Evaluate all rules against a single entity.

        Args:
            entity: Dictionary containing entity data
            id_field: Field name for entity ID
            name_field: Field name for entity display name

        Returns:
            List of Alert objects for triggered rules
        """
        alerts = []
        entity_id = str(entity.get(id_field, "unknown"))
        entity_name = str(entity.get(name_field, entity_id))

        for rule in self.rules.values():
            if not rule.enabled:
                continue

            try:
                if rule.condition(entity):
                    alert = self._create_alert(rule, entity, entity_id, entity_name)
                    alerts.append(alert)
            except Exception as e:
                logger.error(f"Error evaluating rule '{rule.rule_id}' for entity '{entity_id}': {e}")

        return alerts

    def evaluate_all(
        self,
        entities: List[Dict[str, Any]],
        id_field: str = "id",
        name_field: str = "name",
        sort_by_severity: bool = True
    ) -> List[Alert]:
        """
        Evaluate all rules against all entities.

        Args:
            entities: List of entity dictionaries
            id_field: Field name for entity ID
            name_field: Field name for entity display name
            sort_by_severity: Whether to sort results by severity

        Returns:
            List of Alert objects, optionally sorted by severity
        """
        all_alerts = []

        for entity in entities:
            alerts = self.evaluate_entity(entity, id_field, name_field)
            all_alerts.extend(alerts)

        if sort_by_severity:
            all_alerts.sort(key=lambda a: (a.severity.priority, a.timestamp))

        return all_alerts

    def _create_alert(
        self,
        rule: AlertRule,
        entity: Dict[str, Any],
        entity_id: str,
        entity_name: str
    ) -> Alert:
        """Create an alert from a triggered rule."""
        self._alert_counter += 1

        # Format message with entity data
        message = rule.message_template
        if message:
            try:
                message = message.format(**entity)
            except KeyError as e:
                logger.warning(f"Missing field in message template: {e}")
                message = rule.name

        if not message:
            message = f"{rule.name} triggered for {entity_name}"

        return Alert(
            alert_id=f"ALERT-{self._alert_counter:06d}",
            rule_id=rule.rule_id,
            rule_name=rule.name,
            entity_id=entity_id,
            entity_name=entity_name,
            severity=rule.severity,
            category=rule.category,
            message=message,
            context={
                "rule_description": rule.description,
                "entity_data": {k: v for k, v in entity.items()
                               if not callable(v) and k not in ["password", "secret", "token"]}
            }
        )

    def get_rules_summary(self) -> List[Dict[str, Any]]:
        """Get summary of all rules."""
        return [
            {
                "rule_id": rule.rule_id,
                "name": rule.name,
                "severity": rule.severity.value,
                "category": rule.category.value,
                "enabled": rule.enabled,
                "description": rule.description
            }
            for rule in self.rules.values()
        ]

    def get_alert_statistics(self, alerts: List[Alert]) -> Dict[str, Any]:
        """Get statistics about a list of alerts."""
        if not alerts:
            return {
                "total": 0,
                "by_severity": {},
                "by_category": {},
                "by_rule": {}
            }

        by_severity = {}
        by_category = {}
        by_rule = {}

        for alert in alerts:
            # By severity
            sev = alert.severity.value
            by_severity[sev] = by_severity.get(sev, 0) + 1

            # By category
            cat = alert.category.value
            by_category[cat] = by_category.get(cat, 0) + 1

            # By rule
            by_rule[alert.rule_id] = by_rule.get(alert.rule_id, 0) + 1

        return {
            "total": len(alerts),
            "by_severity": by_severity,
            "by_category": by_category,
            "by_rule": by_rule,
            "critical_count": by_severity.get("Critical", 0),
            "high_count": by_severity.get("High", 0),
            "acknowledged_count": sum(1 for a in alerts if a.acknowledged),
            "unresolved_count": sum(1 for a in alerts if not a.resolved)
        }


# =============================================================================
# Pre-built Rule Sets (Factory Functions)
# =============================================================================

def create_contract_alert_rules() -> List[AlertRule]:
    """Create standard alert rules for contract monitoring."""
    return [
        AlertRule(
            rule_id="cost_overrun_warning",
            name="Cost Overrun Warning",
            description="Cost variance between 10-20%",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.COST,
            condition=lambda c: 10 < c.get("cost_variance", 0) <= 20,
            message_template="Cost overrun warning: {cost_variance}% over budget for {name}"
        ),
        AlertRule(
            rule_id="cost_overrun_critical",
            name="Critical Cost Overrun",
            description="Cost variance exceeds 20%",
            severity=AlertSeverity.CRITICAL,
            category=AlertCategory.COST,
            condition=lambda c: c.get("cost_variance", 0) > 20,
            message_template="CRITICAL: {name} is {cost_variance}% over budget"
        ),
        AlertRule(
            rule_id="schedule_delay_warning",
            name="Schedule Delay Warning",
            description="Schedule extended by 10-20%",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.SCHEDULE,
            condition=lambda c: 10 < c.get("schedule_variance", 0) <= 20,
            message_template="Schedule delay: {name} is {schedule_variance}% behind"
        ),
        AlertRule(
            rule_id="schedule_delay_critical",
            name="Critical Schedule Delay",
            description="Schedule extended by more than 20%",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.SCHEDULE,
            condition=lambda c: c.get("schedule_variance", 0) > 20,
            message_template="Critical delay: {name} is {schedule_variance}% behind schedule"
        ),
        AlertRule(
            rule_id="contract_expiring_soon",
            name="Contract Expiring Soon",
            description="Contract expires within 30 days",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.EXPIRATION,
            condition=lambda c: 0 < c.get("days_to_expiry", 999) <= 30,
            message_template="{name} expires in {days_to_expiry} days"
        ),
        AlertRule(
            rule_id="low_health_score",
            name="Low Health Score",
            description="Overall health score below 50",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.PERFORMANCE,
            condition=lambda c: c.get("health_score", 100) < 50,
            message_template="{name} has critical health score of {health_score}"
        ),
        AlertRule(
            rule_id="excessive_change_orders",
            name="Excessive Change Orders",
            description="More than 3 change orders",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.OPERATIONAL,
            condition=lambda c: c.get("change_order_count", 0) > 3,
            message_template="{name} has {change_order_count} change orders"
        ),
        AlertRule(
            rule_id="missing_compliance",
            name="Missing Compliance Documentation",
            description="Required compliance items not verified",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.COMPLIANCE,
            condition=lambda c: not c.get("compliance_verified", True),
            message_template="{name} has unverified compliance requirements"
        ),
        AlertRule(
            rule_id="no_recent_activity",
            name="No Recent Activity",
            description="No updates in 60+ days",
            severity=AlertSeverity.LOW,
            category=AlertCategory.OPERATIONAL,
            condition=lambda c: c.get("days_since_update", 0) > 60,
            message_template="{name} has no activity for {days_since_update} days"
        ),
    ]


def create_workforce_alert_rules() -> List[AlertRule]:
    """Create alert rules for workforce planning."""
    return [
        AlertRule(
            rule_id="understaffing_critical",
            name="Critical Understaffing",
            description="Staffing below 70% of requirement",
            severity=AlertSeverity.CRITICAL,
            category=AlertCategory.OPERATIONAL,
            condition=lambda s: s.get("staffing_ratio", 1.0) < 0.70,
            message_template="CRITICAL: {shift_name} is only {staffing_ratio:.0%} staffed"
        ),
        AlertRule(
            rule_id="understaffing_warning",
            name="Understaffing Warning",
            description="Staffing between 70-85% of requirement",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.OPERATIONAL,
            condition=lambda s: 0.70 <= s.get("staffing_ratio", 1.0) < 0.85,
            message_template="{shift_name} is only {staffing_ratio:.0%} staffed"
        ),
        AlertRule(
            rule_id="overstaffing_warning",
            name="Overstaffing Warning",
            description="Staffing exceeds 115% of requirement",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.COST,
            condition=lambda s: s.get("staffing_ratio", 1.0) > 1.15,
            message_template="{shift_name} is overstaffed at {staffing_ratio:.0%}"
        ),
        AlertRule(
            rule_id="high_overtime",
            name="High Overtime",
            description="Overtime exceeds 20% of labor hours",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.COST,
            condition=lambda s: s.get("overtime_ratio", 0) > 0.20,
            message_template="High overtime ({overtime_ratio:.0%}) on {shift_name}"
        ),
        AlertRule(
            rule_id="low_productivity",
            name="Low Productivity",
            description="Productivity below 80% target",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.PERFORMANCE,
            condition=lambda s: s.get("productivity_rate", 1.0) < 0.80,
            message_template="{shift_name} productivity at {productivity_rate:.0%}"
        ),
        AlertRule(
            rule_id="high_absenteeism",
            name="High Absenteeism",
            description="Absenteeism exceeds 10%",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.OPERATIONAL,
            condition=lambda s: s.get("absenteeism_rate", 0) > 0.10,
            message_template="High absenteeism ({absenteeism_rate:.0%}) on {shift_name}"
        ),
    ]


def create_financial_alert_rules() -> List[AlertRule]:
    """Create alert rules for financial monitoring."""
    return [
        AlertRule(
            rule_id="budget_exceeded",
            name="Budget Exceeded",
            description="Spending exceeds budget",
            severity=AlertSeverity.CRITICAL,
            category=AlertCategory.COST,
            condition=lambda f: f.get("actual", 0) > f.get("budget", float('inf')),
            message_template="Budget exceeded: ${actual:,.0f} vs ${budget:,.0f} budget"
        ),
        AlertRule(
            rule_id="budget_warning",
            name="Budget Warning",
            description="Spending at 90%+ of budget",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.COST,
            condition=lambda f: 0.90 <= f.get("actual", 0) / max(f.get("budget", 1), 1) < 1.0,
            message_template="Budget 90%+ consumed: ${actual:,.0f} of ${budget:,.0f}"
        ),
        AlertRule(
            rule_id="invoice_overdue",
            name="Invoice Overdue",
            description="Invoice past due date",
            severity=AlertSeverity.HIGH,
            category=AlertCategory.COMPLIANCE,
            condition=lambda f: f.get("days_overdue", 0) > 0,
            message_template="Invoice {invoice_id} is {days_overdue} days overdue"
        ),
        AlertRule(
            rule_id="unusual_transaction",
            name="Unusual Transaction",
            description="Transaction significantly above average",
            severity=AlertSeverity.MEDIUM,
            category=AlertCategory.SECURITY,
            condition=lambda f: f.get("amount", 0) > f.get("avg_amount", 0) * 3,
            message_template="Unusual transaction: ${amount:,.0f} (3x average)"
        ),
    ]


# =============================================================================
# Demo / Test
# =============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("ALERT RULES ENGINE DEMO")
    print("=" * 60)

    # Create engine with contract rules
    engine = AlertRulesEngine(create_contract_alert_rules())

    print(f"\nLoaded {len(engine.rules)} alert rules:")
    for rule in engine.get_rules_summary():
        print(f"  [{rule['severity']}] {rule['name']}")

    # Sample contracts to evaluate
    contracts = [
        {
            "id": "C001",
            "name": "IT Infrastructure Upgrade",
            "cost_variance": 25,
            "schedule_variance": 5,
            "health_score": 45,
            "days_to_expiry": 90,
            "change_order_count": 2,
            "compliance_verified": True,
            "days_since_update": 10
        },
        {
            "id": "C002",
            "name": "Office Renovation",
            "cost_variance": 8,
            "schedule_variance": 0,
            "health_score": 85,
            "days_to_expiry": 25,
            "change_order_count": 1,
            "compliance_verified": True,
            "days_since_update": 5
        },
        {
            "id": "C003",
            "name": "Security System Install",
            "cost_variance": 15,
            "schedule_variance": 25,
            "health_score": 60,
            "days_to_expiry": 180,
            "change_order_count": 5,
            "compliance_verified": False,
            "days_since_update": 75
        },
    ]

    print("\n" + "-" * 40)
    print("Evaluating 3 contracts...")

    alerts = engine.evaluate_all(contracts)

    print(f"\nGenerated {len(alerts)} alerts:")
    for alert in alerts:
        print(f"\n  [{alert.severity.value}] {alert.rule_name}")
        print(f"    Entity: {alert.entity_name}")
        print(f"    Message: {alert.message}")

    # Statistics
    stats = engine.get_alert_statistics(alerts)
    print("\n" + "-" * 40)
    print("Alert Statistics:")
    print(f"  Total: {stats['total']}")
    print(f"  Critical: {stats['critical_count']}")
    print(f"  High: {stats['high_count']}")
    print(f"  By Category: {stats['by_category']}")
